version: '3.4'

services:
  best-practices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "80"
    ports:
      - "5101:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
